#!/bin/bash

# Get the directory of the script
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# Go to the project root (parent of scripts directory)
cd "$SCRIPT_DIR/.."

# Extract liqo version from go.mod and generate liqo_version.go
VERSION=$(grep 'github.com/liqotech/liqo' go.mod | awk '{print $2}')

if [ -z "$VERSION" ]; then
    echo "Error: Could not find liqo version in go.mod"
    exit 1
fi

cat > liqo/liqo_version.go << EOF
// Code generated by generate_version.sh; DO NOT EDIT.

package liqo

// LiqoVersion is the version of liqo dependency extracted from go.mod at build time
const LiqoVersion = "$VERSION"
EOF

echo "Generated liqo_version.go with version: $VERSION"
